### ISSUE TITLE
Magic Wand example, try to change the structure but shape mismatch

### ISSUE THREAD

**Issue by jianian0318** [tensorflow/tflite-micro#1711]
Dear tflite team,
I tried to change the structure of your Magic Wand example for more labels. I want the model to have 7 output, so I just changed the last layer from:
```tf.keras.layers.Dense(4, activation="softmax")  # (batch, 4)```
to:
```tf.keras.layers.Dense(7, activation="softmax") ```
so that the “build_cnn” function looks like this:
```
def build_cnn(seq_length):
  model = tf.keras.Sequential([
      tf.keras.layers.Conv2D(
          8, (4, 3),
          padding="same",
          activation="relu",
          input_shape=(seq_length, 3, 1)),  # output_shape=(batch, 128, 3, 8)
      tf.keras.layers.MaxPool2D((3, 3)),  # (batch, 42, 1, 8)
      tf.keras.layers.Dropout(0.1),  # (batch, 42, 1, 8)
      tf.keras.layers.Conv2D(16, (4, 1), padding="same",
                             activation="relu"),  # (batch, 42, 1, 16)
      tf.keras.layers.MaxPool2D((3, 1), padding="same"),  # (batch, 14, 1, 16)
      tf.keras.layers.Dropout(0.1),  # (batch, 14, 1, 16)
      tf.keras.layers.Flatten(),  # (batch, 224)
      tf.keras.layers.Dense(16, activation="relu"),  # (batch, 16)
      tf.keras.layers.Dropout(0.1),  # (batch, 16)
      tf.keras.layers.Dense(7, activation="softmax") 
  ])
  model_path = os.path.join("./netmodels", "CNN")
  print("Built CNN.")
  if not os.path.exists(model_path):
    os.makedirs(model_path)
  model.load_weights("./netmodels/CNN/weights.h5")
  return model, model_path
```
However, there was shape mismatch when I begun training:
```
Start to build net...
Built CNN.
Traceback (most recent call last):
  File "train.py", line 194, in <module>
    model, model_path = build_net(args, seq_length)
  File "train.py", line 103, in build_net
    model, model_path = build_cnn(seq_length)
  File "train.py", line 72, in build_cnn
    model.load_weights("./netmodels/CNN/weights.h5")
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/keras/backend.py", line 4028, in batch_set_value
    x.assign(np.asarray(value, dtype=dtype_numpy(x)))
ValueError: Cannot assign value to variable ' dense_1/kernel:0': Shape mismatch.The variable shape (16, 7), and the assigned value shape (16, 4) are incompatible.
```
Is there other params that specify the number of output to be 4? Or what else adjustment should I make to handle this error? 
Any help will be appreciated!

**Comment by jianian0318** [comment]
Sry to bother, I figured it out. The "weights.h5" file in the project is used to stored the params. The original "weights.h5" file provided has objects "kernel:0"(shape is (,4)) and "bias:0"(shape is (16,4)). What I need to do is to change them into the shape of (,7) and (16,7) respectively to fit my own model structure. Problem solved!
