### ISSUE TITLE
STM32F4 Build generates error `OSError: [Errno 8] Exec format error`

### ISSUE THREAD

**Issue by NevynUK** [tensorflow/tflite-micro#1857]
I have recently downloaded TFLite-Micro and I am trying to get the system building for Cortex-M4 with the aim of moving to Cortex-M7.

From the cloned directory `tflite-micro` I am executing the command:

`make -f tensorflow/lite/micro/tools/make/Makefile TARGET=stm32f4 TARGET_ARCH=cortex-m4`

Build looks to go OK until what looks like the test phase of the build when I get the following error:

```
/Users/HOME_DIR/GitHub/tflite-micro/tensorflow/lite/micro/testing/../tools/make/downloads/renode/renode-test /tmp/renode_stm32f4_logs/stm32f4.robot   -r /tmp/renode_stm32f4_logs   --variable RESC:/Users/HOME_DIR/GitHub/tflite-micro/tensorflow/lite/micro/testing/../testing/stm32f4.resc   --variable UART_LOG:/tmp/renode_stm32f4_logs/uart_log.txt

Preparing suites
Traceback (most recent call last):
  File "/Users/HOME_DIR/GitHub/tflite-micro/tensorflow/lite/micro/tools/make/downloads/renode/tests/run_tests.py", line 40, in <module>
    tests_engine.run()
  File "/Users/HOME_DIR/GitHub/tflite-micro/tensorflow/lite/micro/tools/make/downloads/renode/tests/tests_engine.py", line 330, in run
    res = suite.prepare(options)
  File "/Users/HOME_DIR/GitHub/tflite-micro/tensorflow/lite/micro/tools/make/downloads/renode/tests/robot_tests_provider.py", line 280, in prepare
    RobotTestSuite.robot_frontend_process = self._run_remote_server(options, port_offset=self.port_offset)
  File "/Users/HOME_DIR/GitHub/tflite-micro/tensorflow/lite/micro/tools/make/downloads/renode/tests/robot_tests_provider.py", line 338, in _run_remote_server
    p = subprocess.Popen(args, cwd=self.remote_server_directory, bufsize=1)
  File "/Users/HOME_DIR/.pyenv/versions/3.10.9/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/HOME_DIR/.pyenv/versions/3.10.9/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/HOME_DIR/GitHub/tflite-micro/tensorflow/lite/micro/tools/make/downloads/renode/renode'
make: *** [tensorflow/lite/micro/tools/make/targets/stm32f4_makefile.inc:110: test] Error 1
```

Has anyone seen this or have a resolution?

**Comment by NevynUK** [comment]
I think I may have found the answer, the renode download script is downloading the Linux system and I am running on MacOS.
