### ISSUE TITLE
bazel fails with AttributeError: 'PathDistribution' object has no attribute '_normalized_name'

### ISSUE THREAD

**Issue by rkuester** [tensorflow/tflite-micro#2027]
In some Python environments, bazel fails with the error:

    AttributeError: 'PathDistribution' object has no attribute '_normalized_name'

as it creates external repositories for the Python packages in `third_party/python_requirements.txt`.

I noticed this in tensorflow/tflite-micro@b09b33e557f0c231fedda34bc99143c0e4e406e6 with Python 3.11, Bazel 6.2.1, and Debian Bookworm, though it may not be limited to this environment.

<details>
<summary>Verbose error message</summary>

````
INFO: Repository tflm_pip_deps_wrapt instantiated at:
  /home/rkuester/wetu/tflite-micro/WORKSPACE:44:13: in <toplevel>
  /home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/tflm_pip_deps/requirements.bzl:56:20: in install_deps
Repository rule whl_library defined at:
  /home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/rules_python/python/pip_install/pip_repository.bzl:574:30: in <toplevel>
ERROR: An error occurred during the fetch of repository 'tflm_pip_deps_wrapt':
   Traceback (most recent call last):
        File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/rules_python/python/pip_install/pip_repository.bzl", line 550, column 13, in _whl_library_impl
                fail("whl_library %s failed: %s (%s)" % (rctx.attr.name, result.stdout, result.stderr))
Error in fail: whl_library tflm_pip_deps_wrapt failed: Collecting wrapt==1.14.1
  Using cached wrapt-1.14.1.tar.gz (50 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
 (  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-aodav9l0/wrapt.egg-info
      writing /tmp/pip-pip-egg-info-aodav9l0/wrapt.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-aodav9l0/wrapt.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-pip-egg-info-aodav9l0/wrapt.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-aodav9l0/wrapt.egg-info/SOURCES.txt'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-wheel-eoslx5pp/wrapt_b4609696e12d4d47a60c10795409f38a/setup.py", line 41, in <module>
          setuptools.setup(
        File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/pypi__setuptools/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/pypi__setuptools/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/pypi__setuptools/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/pypi__setuptools/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/pypi__setuptools/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/pypi__setuptools/setuptools/command/egg_info.py", line 298, in run
          self.find_sources()
        File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/pypi__setuptools/setuptools/command/egg_info.py", line 305, in find_sources
          mm.run()
        File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/pypi__setuptools/setuptools/command/egg_info.py", line 540, in run
          self.add_defaults()
        File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/pypi__setuptools/setuptools/command/egg_info.py", line 577, in add_defaults
          sdist.add_defaults(self)
        File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/pypi__setuptools/setuptools/_distutils/command/sdist.py", line 226, in add_defaults
          self._add_defaults_python()
        File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/pypi__setuptools/setuptools/command/sdist.py", line 111, in _add_defaults_python
          build_py = self.get_finalized_command('build_py')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/pypi__setuptools/setuptools/_distutils/cmd.py", line 298, in get_finalized_command
          cmd_obj = self.distribution.get_command_obj(command, create)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/pypi__setuptools/setuptools/_distutils/dist.py", line 858, in get_command_obj
          klass = self.get_command_class(command)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/pypi__setuptools/setuptools/dist.py", line 914, in get_command_class
          eps = metadata.entry_points(group='distutils.commands', name=command)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1040, in entry_points
          return SelectableGroups.load(eps).select(**params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 476, in load
          ordered = sorted(eps, key=by_group)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1037, in <genexpr>
          eps = itertools.chain.from_iterable(
                                             ^
        File "/usr/lib/python3.11/importlib/metadata/_itertools.py", line 16, in unique_everseen
          k = key(element)
              ^^^^^^^^^^^^
      AttributeError: 'PathDistribution' object has no attribute '_normalized_name'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/rules_python/python/pip_install/extract_wheels/extract_single_wheel.py", line 105, in <module>
    main()
  File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/rules_python/python/pip_install/extract_wheels/extract_single_wheel.py", line 81, in main
    subprocess.run(pip_args, check=True, env=env)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--isolated', 'wheel', '--no-deps', '-r', '/tmp/tmpiyhimq2n']' returned non-zero exit status 1.
)
````

</details>

**Comment by rkuester** [comment]
This seems to be some complex interplay between changes to Python setuptools, importlib, and the metadata or lack thereof in older Python packages (distributions). See https://github.com/python/importlib_metadata/issues/396 and friends.

This is perhaps exacerbated by the way bazel sets up its own Python environment which falls through to the system Python environment in some cases. A [hermetic Python toolchain](https://github.com/bazelbuild/rules_python#toolchain-registration) in bazel might help; however, it's not clear whether that toolchain or the system toolchain is used during the creation of external repositories.

**Comment by rkuester** [comment]
Removing the Python package [pbr](https://docs.openstack.org/pbr/latest/) from failing environment (Python 3.11, Bazel 6.2.1, and Debian Bookworm) caused the problem to go away. *pbr* intentionally mucks with the behavior of setuptools, so it's not a stretch to imagine it perturbs the apparently delicate setuptools–importlib interaction.

**Comment by rkuester** [comment]
Not exploring further given the above workaround.
