### ISSUE TITLE
bazel builds in environments with Python 3.11 fail due to changes in Py package wrapt

### ISSUE THREAD

**Issue by rkuester** [tensorflow/tflite-micro#2264]
bazel builds in environments with Python 3.11 fail when downloading external repositories, because the Python package `wrapt` downloaded from PyPI no longer matches the hash pinned in third_party/python_requirements.txt. The error looks like the following:

````
ERROR: An error occurred during the fetch of repository 'tflm_pip_deps_wrapt':
   Traceback (most recent call last):
        File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/rules_python/python/pip_install/pip_repository.bzl", line 691, column 13, in _whl_library_impl
                fail("whl_library %s failed: %s (%s) error code: '%s'" % (rctx.attr.name, result.stdout, result.stderr, result.return_code))
Error in fail: whl_library tflm_pip_deps_wrapt failed: Collecting wrapt==1.14.1
  Using cached wrapt-1.14.1-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (78 kB)
 (ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    wrapt==1.14.1 from https://files.pythonhosted.org/packages/7f/1b/e0439eec0db6520968c751bc7e12480bb80bb8d939190e0e55ed762f3c7a/wrapt-1.14.1-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from -r /tmp/tmpu0cqm4v9 (line
 1)):
        Expected sha256 00b6d4ea20a906c0ca56d84f93065b398ab74b927a7a3dbd470f6fc503f95dc3
        Expected     or 01c205616a89d09827986bc4e859bcabd64f5a0662a7fe95e0d359424e0e071b
        Expected     or 02b41b633c6261feff8ddd8d11c711df6842aba629fdd3da10249a53211a72c4
[....]
        Expected     or ef3f72c9666bba2bab70d2a8b79f2c6d2c1a42a7f7e2b0ec83bb2f9e383950af
             Got        a9008dad07d71f68487c91e96579c8567c98ca4c3881b9b113bc7b33e9fd78b8

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/rules_python/python/pip_install/tools/wheel_installer/wheel_installer.py", line 452, in <module>
    main()
  File "/home/rkuester/.cache/bazel/_bazel_rkuester/41790abb24926c9e17fa640f85512e6d/external/rules_python/python/pip_install/tools/wheel_installer/wheel_installer.py", line 429, in main
    subprocess.run(pip_args, check=True, env=env)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/rkuester/tmp/venv/bin/python3', '-m', 'pip', '--isolated', 'wheel', '--no-deps', '-r', '/tmp/tmpu0cqm4v9']' returned non-zero exit status 1.
) error code: '1'
````

**Comment by rkuester** [comment]
Investigating in wrapt's PyPI and Github projects, it appears they (accidentally?) [rebuilt](https://github.com/GrahamDumpleton/wrapt/commits/1.14.x) and [reuploaded](https://pypi.org/project/wrapt/1.14.1/#files) the v1.14.1 packages for CPython 3.11 a mere 12 hours ago. Compare with the dates on the packages for other Python versions, unchanged from May 2022. This explains why builds failed just now, and only on CPython 3.11.

As this upload was made by the wrapt project owners, It seems safe for us to update our hashes and carry on.
