### ISSUE TITLE
Shape assertion and unintialized memory in Conv2D

### ISSUE THREAD

**Issue by cosw0t** [tensorflow/tflite-micro#2338]
I have a simple keras model made of a Conv2D with dilation_rate of 2 - converted to tflite and int8-quantized

the first issue is in main and the error is reading the shapes in, the assertion here:
https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/kernels/internal/types.h
called from here:
https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/kernels/internal/reference/integer_ops/conv.h#L52C4

Here's the branch to reproduce: https://github.com/cosw0t/tflite-micro/tree/bug_report/conv2d_main
Command:
```
bazel run tensorflow/lite/micro/examples/bug_report_conv2d:bug_report_conv2d_test
```

It asserts because it has stored input shape: `[4, 1, 49, 3]` and output shape: `[1, 1, 45, 30]`, but the input shape is wrong, it should be [1, 1, 49, 3]. The shape is correctly reported by Netron as `[1, 1, 49, 3]`.

Second issue:
Following the discussion in #2336 I have rebased onto https://github.com/rascani/tflite-micro/tree/initialize_values that fixes #2337, however it doesn't include #2335 that is instead in main.

Msan still complains about uninitialized memory. The model is the same.

Here's the branch to reproduce: https://github.com/cosw0t/tflite-micro/tree/bug_report/conv2d_2337
Command:
```
bazel run --config msan tensorflow/lite/micro/examples/bug_report_conv2d:bug_report_conv2d_test
```

output:

```
==637541==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7f9d3ceca0da in int gemmlowp::SaturatingRoundingDoublingHighMul<int>(int, int) /proc/self/cwd/external/gemmlowp/fixedpoint/fixedpoint.h:342:26
    #1 0x7f9d3ceca0da in tflite::MultiplyByQuantizedMultiplierSmallerThanOneExp(int, int, int) /proc/self/cwd/./tensorflow/lite/kernels/internal/common.h:359:7
    #2 0x7f9d3ceca0da in tflite::reference_integer_ops::AddFunc(signed char, signed char, tflite::ArithmeticParams const&) /proc/self/cwd/./tensorflow/lite/kernels/internal/reference/integer_ops/add.h:186:7
    #3 0x7f9d3cecba99 in void tflite::reference_integer_ops::ElementWise<signed char>(int, tflite::ArithmeticParams const&, signed char const*, signed char const*, signed char*, void (*)(tflite::ArithmeticParams const&), signed char (*)(signed char, signed char, tflite::ArithmeticParams const&)) /proc/self/cwd/./tensorflow/lite/kernels/internal/reference/integer_ops/add.h:70:22
    #4 0x7f9d3cecba99 in void tflite::reference_integer_ops::BroadcastAddRecursiveDimensions<signed char>(tflite::ArithmeticParams const&, int, unsigned long*, unsigned long*, unsigned long*, unsigned long*, unsigned long*, unsigned long*, signed char const*, signed char const*, signed char*, void (*)(tflite::ArithmeticParams const&), signed char (*)(signed char, signed char, tflite::ArithmeticParams const&)) /proc/self/cwd/./tensorflow/lite/kernels/internal/reference/integer_ops/add.h:116:7
    #5 0x7f9d3cecb72f in void tflite::reference_integer_ops::BroadcastAddRecursiveDimensions<signed char>(tflite::ArithmeticParams const&, int, unsigned long*, unsigned long*, unsigned long*, unsigned long*, unsigned long*, unsigned long*, signed char const*, signed char const*, signed char*, void (*)(tflite::ArithmeticParams const&), signed char (*)(signed char, signed char, tflite::ArithmeticParams const&)) /proc/self/cwd/./tensorflow/lite/kernels/internal/reference/integer_ops/add.h:86:7
    #6 0x7f9d3cecb72f in void tflite::reference_integer_ops::BroadcastAddRecursiveDimensions<signed char>(tflite::ArithmeticParams const&, int, unsigned long*, unsigned long*, unsigned long*, unsigned long*, unsigned long*, unsigned long*, signed char const*, signed char const*, signed char*, void (*)(tflite::ArithmeticParams const&), signed char (*)(signed char, signed char, tflite::ArithmeticParams const&)) /proc/self/cwd/./tensorflow/lite/kernels/internal/reference/integer_ops/add.h:86:7
    #7 0x7f9d3cecb72f in void tflite::reference_integer_ops::BroadcastAddRecursiveDimensions<signed char>(tflite::ArithmeticParams const&, int, unsigned long*, unsigned long*, unsigned long*, unsigned long*, unsigned long*, unsigned long*, signed char const*, signed char const*, signed char*, void (*)(tflite::ArithmeticParams const&), signed char (*)(signed char, signed char, tflite::ArithmeticParams const&)) /proc/self/cwd/./tensorflow/lite/kernels/internal/reference/integer_ops/add.h:86:7
    #8 0x7f9d3cecb72f in void tflite::reference_integer_ops::BroadcastAddRecursiveDimensions<signed char>(tflite::ArithmeticParams const&, int, unsigned long*, unsigned long*, unsigned long*, unsigned long*, unsigned long*, unsigned long*, signed char const*, signed char const*, signed char*, void (*)(tflite::ArithmeticParams const&), signed char (*)(signed char, signed char, tflite::ArithmeticParams const&)) /proc/self/cwd/./tensorflow/lite/kernels/internal/reference/integer_ops/add.h:86:7
    #9 0x7f9d3cecb72f in void tflite::reference_integer_ops::BroadcastAddRecursiveDimensions<signed char>(tflite::ArithmeticParams const&, int, unsigned long*, unsigned long*, unsigned long*, unsigned long*, unsigned long*, unsigned long*, signed char const*, signed char const*, signed char*, void (*)(tflite::ArithmeticParams const&), signed char (*)(signed char, signed char, tflite::ArithmeticParams const&)) /proc/self/cwd/./tensorflow/lite/kernels/internal/reference/integer_ops/add.h:86:7
    #10 0x7f9d3cec696e in void tflite::reference_integer_ops::BroadcastBinaryFunction6DSlow<signed char>(tflite::ArithmeticParams const&, tflite::RuntimeShape const&, signed char const*, tflite::RuntimeShape const&, signed char const*, tflite::RuntimeShape const&, signed char*, void (*)(tflite::ArithmeticParams const&), signed char (*)(signed char, signed char, tflite::ArithmeticParams const&)) /proc/self/cwd/./tensorflow/lite/kernels/internal/reference/integer_ops/add.h:161:3
    #11 0x7f9d3cec696e in tflite::reference_integer_ops::BroadcastAdd4DSlow(tflite::ArithmeticParams const&, tflite::RuntimeShape const&, signed char const*, tflite::RuntimeShape const&, signed char const*, tflite::RuntimeShape const&, signed char*) /proc/self/cwd/./tensorflow/lite/kernels/internal/reference/integer_ops/add.h:242:3
    #12 0x7f9d3cec696e in tflite::EvalAddQuantized(TfLiteContext*, TfLiteNode*, TfLiteAddParams*, tflite::OpDataAdd const*, TfLiteEvalTensor const*, TfLiteEvalTensor const*, TfLiteEvalTensor*) /proc/self/cwd/tensorflow/lite/micro/kernels/add.cc:116:9
    #13 0x7f9d3cec7440 in tflite::AddEval(TfLiteContext*, TfLiteNode*) /proc/self/cwd/tensorflow/lite/micro/kernels/add.cc:185:5
    #14 0x7f9d3d11029b in tflite::MicroInterpreterGraph::InvokeSubgraph(int) /proc/self/cwd/tensorflow/lite/micro/micro_interpreter_graph.cc:194:34
    #15 0x7f9d3d121518 in tflite::MicroInterpreter::Invoke() /proc/self/cwd/tensorflow/lite/micro/micro_interpreter.cc:294:17
    #16 0x55a621031cb5 in main /proc/self/cwd/tensorflow/lite/micro/examples/bug_report_conv2d/bug_report_conv2d_test.cc:42:3
    #17 0x7f9d3c7c3d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #18 0x7f9d3c7c3e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #19 0x55a620faab14 in _start (/home/msanna/.cache/bazel/_bazel_msanna/29aa5494e2febf9342269ff9626570df/execroot/tflite_micro/bazel-out/k8-fastbuild/bin/tensorflow/lite/micro/examples/bug_report_conv2d/bug_report_conv2d_test+0x20b14) (BuildId: f6204fdbd63ad98e5b00ef0f901f874dc5005abe)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /proc/self/cwd/external/gemmlowp/fixedpoint/fixedpoint.h:342:26 in int gemmlowp::SaturatingRoundingDoublingHighMul<int>(int, int)
Exiting
```

**Comment by rascani** [comment]
@ddavis-2015

**Comment by rascani** [comment]
Thanks, this example helps. This issue is likely due to #2335, because that reshapes the SpaceToBatch output tensor, which is the input tensor to Conv2d. This was to match TFLite behavior, but I think we likely missed something. I'll probably revert that PR unless there's a simple fix.

**Comment by ddavis-2015** [comment]
@cosw0t Please see #2319 for a workaround when converting your Keras model using the TfLiteConverter, as your issue is specific to using convolution with dilation.

**Comment by cosw0t** [comment]
> @cosw0t Please see #2319 for a workaround when converting your Keras model using the TfLiteConverter, as your issue is specific to using convolution with dilation.

Apologies, I didn't realize that this was the same issue.
It seems to be the case that converting multiple functions is not supported, so if my model has many layers it's not really an option, right?

thanks

**Comment by ddavis-2015** [comment]
PR[#2356](https://github.com/tensorflow/tflite-micro/pull/2356) resolves this issue.

Resolution Verified in Colab.
