### ISSUE TITLE
bazel build failed when fetching repository @tflm_pip_deps_tensorflow

### ISSUE THREAD

**Issue by haozh960** [tensorflow/tflite-micro#2729]
It always fail when bazel build  tflm_model_transforms,

**enviroment,**
tflite-micro verion e86d97b6237f88ab5925c0b41e3e3589a1560d86
Python 3.11.0
Bazel 7.0.0

 **log as below**, 
(py3.10) hawk_zhang@ps:~/code/tflite-micro$ **bazel build tensorflow/lite/micro/tools:tflm_model_transforms**
Starting local Bazel server and connecting to it...
INFO: Repository tflm_pip_deps_tensorflow instantiated at:
  /home/hawk_zhang/code/tflite-micro/WORKSPACE:61:13: in <toplevel>
  /home/hawk_zhang/.cache/bazel/_bazel_hawk_zhang/2eb5c578e46acd6cefa2ac2536ce6685/external/tflm_pip_deps/requirements.bzl:49:20: in install_deps
Repository rule whl_library defined at:
  /home/hawk_zhang/.cache/bazel/_bazel_hawk_zhang/2eb5c578e46acd6cefa2ac2536ce6685/external/rules_python/python/pip_install/pip_repository.bzl:697:30: in <toplevel>
ERROR: An error occurred during the fetch of repository 'tflm_pip_deps_tensorflow':
   Traceback (most recent call last):
        File "/home/hawk_zhang/.cache/bazel/_bazel_hawk_zhang/2eb5c578e46acd6cefa2ac2536ce6685/external/rules_python/python/pip_install/pip_repository.bzl", line 596, column 13, in _whl_library_impl
                fail("whl_library %s failed: %s (%s) error code: '%s'" % (rctx.attr.name, result.stdout, result.stderr, result.return_code))
Error in fail: whl_library tflm_pip_deps_tensorflow failed:  (Timed out) error code: '256'
ERROR: /home/hawk_zhang/code/tflite-micro/WORKSPACE:61:13: fetching whl_library rule //external:tflm_pip_deps_tensorflow: Traceback (most recent call last):
        File "/home/hawk_zhang/.cache/bazel/_bazel_hawk_zhang/2eb5c578e46acd6cefa2ac2536ce6685/external/rules_python/python/pip_install/pip_repository.bzl", line 596, column 13, in _whl_library_impl
                fail("whl_library %s failed: %s (%s) error code: '%s'" % (rctx.attr.name, result.stdout, result.stderr, result.return_code))
Error in fail: whl_library tflm_pip_deps_tensorflow failed:  (Timed out) error code: '256'
ERROR: no such package '@tflm_pip_deps_tensorflow//': whl_library tflm_pip_deps_tensorflow failed:  (Timed out) error code: '256'
ERROR: /home/hawk_zhang/code/tflite-micro/tensorflow/lite/micro/tools/BUILD:123:11: //tensorflow/lite/micro/tools:tflm_model_transforms_lib depends on @tflm_pip_deps_tensorflow//:pkg in repository @tflm_pip_deps_tensorflow which failed to fetch. no such package '@tflm_pip_deps_tensorflow//': whl_library tflm_pip_deps_tensorflow failed:  **(Timed out) error code: '256'**
ERROR: Analysis of target '//tensorflow/lite/micro/tools:tflm_model_transforms' failed; build aborted: Analysis failed
INFO: Elapsed time: 605.242s, Critical Path: 0.15s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully

**Comment by haozh960** [comment]
casued by bazel ctx timeout
